// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6wIDRPDDSU0vv9azcOFwCP-vFXt69rJY',
    appId: '1:5670830973:web:cf1b820de38fc1c20c4214',
    messagingSenderId: '5670830973',
    projectId: 'instagram-clone-gaiseric',
    authDomain: 'instagram-clone-gaiseric.firebaseapp.com',
    storageBucket: 'instagram-clone-gaiseric.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG0ym0ay-qSFc7qKpQ8SHuzNYJ8308rDI',
    appId: '1:5670830973:android:43755e9ccaa680f60c4214',
    messagingSenderId: '5670830973',
    projectId: 'instagram-clone-gaiseric',
    storageBucket: 'instagram-clone-gaiseric.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmv6kiOm3Ua0tsNpfzbiVM5CPsMO65rII',
    appId: '1:5670830973:ios:06944fbb699ddcc80c4214',
    messagingSenderId: '5670830973',
    projectId: 'instagram-clone-gaiseric',
    storageBucket: 'instagram-clone-gaiseric.appspot.com',
    iosClientId: '5670830973-q9ff0qtfa04acvh1m2tuoha8eqgkh7po.apps.googleusercontent.com',
    iosBundleId: 'com.example.instaclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmv6kiOm3Ua0tsNpfzbiVM5CPsMO65rII',
    appId: '1:5670830973:ios:06944fbb699ddcc80c4214',
    messagingSenderId: '5670830973',
    projectId: 'instagram-clone-gaiseric',
    storageBucket: 'instagram-clone-gaiseric.appspot.com',
    iosClientId: '5670830973-q9ff0qtfa04acvh1m2tuoha8eqgkh7po.apps.googleusercontent.com',
    iosBundleId: 'com.example.instaclone',
  );
}
